index:
  class: File
  path: /home/scontaldo/variantCalling/hg38-20221027/indexGenome/hg38.fa
threads: 21 
db_path:
  class: File
  path: /fungi/krakenDB/Virus/hash.k2d
fastq_directory:
  class: Directory
  location: data 
